export type ValidSkills =
  | "Python"
  | "SQL"
  | "JavaScript"
  | "TypeScript"
  | "PyTorch"
  | "TensorFlow"
  | "Scikit-learn"
  | "NumPy"
  | "Pandas"
  | "Spark"
  | "Airflow"
  | "MLflow"
  | "LangChain"
  | "FastAPI"
  | "Flask"
  | "PostgreSQL"
  | "MySQL"
  | "MongoDB"
  | "Redis"
  | "AWS"
  | "Docker"
  | "Kubernetes"
  | "Git"
  | "Linux"
  | "REST APIs"
  | "Distributed Systems"
  | "Data Pipelines"
  | "ETL"
  | "Feature Engineering"
  | "Model Evaluation"
  | "Uncertainty Estimation"
  | "Time Series"
  | "Anomaly Detection"
  | "Computer Vision"
  | "NLP"
  | "Multimodal Models"
  | "Transformers"
  | "Diffusion Models"
  | "React"
  | "Next.js"
  | "Tailwind CSS"
  | "Vercel";
