export const siteConfig = {
  name: "Ruizhe (Jason) Dai - Data Science & ML Engineer",
  authorName: "Ruizhe (Jason) Dai",
  username: "jason-dai9",
  description:
    "Ruizhe (Jason) Dai is a Data Science and Machine Learning engineer focused on building data-driven systems and AI-assisted tools. Experience includes disease progression modeling, multimodal model evaluation, and large-scale data pipelines across research and industry.",
  url: "https://YOUR_DOMAIN.com",
  links: {
    github: "https://github.com/YOUR_GITHUB_USERNAME",
    linkedin: "https://www.linkedin.com/in/jason-dai9",
    email: "mailto:dai9@seas.upenn.edu",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "/og.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Ruizhe Dai",
    "Jason Dai",
    "Data Science",
    "Machine Learning",
    "ML Engineering",
    "AI Systems",
    "Python",
    "SQL",
    "PyTorch",
    "Scikit-Learn",
    "Generative AI",
    "NLP",
    "Spark",
    "Airflow",
    "AWS",
    "PostgreSQL",
    "Distributed Systems",
    "University of Pennsylvania",
    "UC San Diego",
    "OPTIC Lab",
    "Halıcıoglu Data Science Institute",
    "Disease progression modeling",
    "Uncertainty evaluation",
  ],
};
