export const siteConfig = {
  name: "Ruizhe（Jason）Dai｜数据科学 & 机器学习工程",
  authorName: "Ruizhe（Jason）Dai",
  username: "jason-dai9",
  description:
    "Ruizhe（Jason）Dai，数据科学与机器学习工程方向，关注数据驱动系统与 AI 辅助工具。经历包括疾病进展建模、多模态模型评测与大规模数据管道（研究与工业实践）。",
  url: "https://YOUR_DOMAIN.com",
  links: {
    github: "https://github.com/JasonDai1219",
    linkedin: "https://www.linkedin.com/in/jason-dai9",
    email: "mailto:dai9@seas.upenn.edu",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "/og.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "戴睿哲",
    "Ruizhe Dai",
    "Jason Dai",
    "数据科学",
    "机器学习",
    "ML 工程",
    "AI 系统",
    "Python",
    "SQL",
    "PyTorch",
    "Scikit-learn",
    "生成式 AI",
    "NLP",
    "Spark",
    "Airflow",
    "AWS",
    "PostgreSQL",
    "分布式系统",
    "宾夕法尼亚大学",
    "加州大学圣地亚哥分校",
    "OPTIC Lab",
    "Halıcıoglu Data Science Institute",
    "疾病进展建模",
    "不确定性评估",
  ],
};